service: web-api

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  profile: slsProfile
  region: us-east-1
  stage: ${self:custom.secrets.NODE_ENV}
  timeout: 30
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
    USERNAME: ${self:custom.secrets.USERNAME}
    PASSWORD: ${self:custom.secrets.PASSWORD}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}

functions:
  authorize:
    handler: functions/authorize.handler
  healthCheck:
    handler: functions/healthCheck.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  login:
    handler: functions/login.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
  create:
    handler: functions/create.handler
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: authorize
  getOne:
    handler: functions/getOne.handler
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: authorize
  getAll:
    handler: functions/getAll.handler
    events:
     - http:
         path: notes
         method: get
         cors: true
         authorizer: authorize
  update:
    handler: functions/update.handler
    events:
     - http:
         path: notes/{id}
         method: put
         cors: true
         authorizer: authorize
  destroy:
    handler: functions/destroy.handler
    events:
     - http:
         path: notes/{id}
         method: delete
         cors: true
         authorizer: authorize

plugins:
  - serverless-offline